{{- if .Values.telegramAllowFrom }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openclaw-with-brain.fullname" . }}-credentials
  labels:
    {{- include "openclaw-with-brain.labels" . | nindent 4 }}
data:
  telegram-default-allowFrom.json: |
    {
      "version": 1,
      "allowFrom": {{ .Values.telegramAllowFrom | toJson }}
    }
{{- end }}
